version: "3.8"

services:
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    restart: unless-stopped
    user: "1000:1000"
    env_file: ./.env
    command:
      # We use variables for all parts, including the user and host
      - "--redis.addr=redis://${REDIS_USER}:${GABRIEL_REDIS_PASS}@${REDIS_HOST_PORT}"
    network_mode: host
    volumes:
      - ./configs/redis_exporter.conf:/etc/redis_exporter.conf:ro

  sentinel-exporter:
    image: oliver006/redis_exporter:latest
    container_name: sentinel-exporter
    restart: unless-stopped
    user: "1000:1000"
    env_file: ./.env
    command:
      - "--web.listen-address=:9355"
      # We use variables for all parts, including the user and host
      - "--redis.addr=redis://${SENTINEL_USER}:${CHRISTOPHER_REDIS_PASS}@${SENTINEL_HOST_PORT}"
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: "0:0"
    volumes:
      # This file will be generated by setup.sh
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./volumes/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    network_mode: host

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    user: "0:0"
    env_file: ./.env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      # This file will be generated by setup.sh
      - ./configs/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./provisioning/alerting:/etc/grafana/provisioning/alerting:ro
    network_mode: host

volumes:
  prometheus_data:
  grafana_data:
